server:
  port: 8080
  
spring:
  application:
    name: trade-viewer
  cloud:
    config:
      uri:  ${vcap.services.config-server.credentials.uri:http://cloud-config:8888}
  main:
    allow-bean-definition-overriding: "true"
eureka:
  client:
    enabled: false
    
logging:
  level:
    org.springframework: DEBUG