server:
  port: 8080
  
spring:
  application:
    name: trade-viewer
  cloud:
    config:
      uri:  ${vcap.services.config-server.credentials.uri:http://cloud-config:8888}
  main:
    allow-bean-definition-overriding: "true"
eureka:
    client:
        fetch-registry: true
EUREKA_PORT_8761_TCP_ADDR: ${vcap.services.eureka-service.credentials.uri:localhost}