server:
  port: 8080
  
logging:
  level:
    org.springframework: DEBUG
spring:
  application:
    name: trade-viewer
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: "true"
eureka:
    client:
        fetch-registry: true